name: flutter_notes_app
description: "flutter-notes-app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  outline_material_icons: ^1.0.0
  sqflite: ^2.3.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  share_plus: ^10.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
